name: Create Project Angular MFE

on:
  issues:
    types: [opened]

jobs:
  create-repo:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'create:')
    env:
      GH_TOKEN: ${{ secrets.PAT_TOKEN }} # Token com escopo repo
    steps:
      - name: Extrair nome do projeto da issue
        id: extract
        run: |
          ISSUE_TITLE="${{ github.event.issue.title }}"
          PROJECT_NAME=$(echo "$ISSUE_TITLE" | sed 's/^create://')
          echo "PROJECT_NAME=$PROJECT_NAME" >> $GITHUB_ENV
          echo "project-name=$PROJECT_NAME" >> $GITHUB_OUTPUT

      - name: Criar repositório do template
        run: |
          gh repo create $PROJECT_NAME \
            --private \
            --template "vyracare/repo-template-angular" \
            --clone

      - name: Rodar script de rename
        run: |
          cd $PROJECT_NAME
          chmod +x rename-angular-project.sh
          ./rename-angular-project.sh $PROJECT_NAME

      - name: Commit e push das mudanças
        run: |
          cd $PROJECT_NAME
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Usa token para autenticação no push
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/vyracare/$PROJECT_NAME.git
          git add .
          git commit -m "chore: rename Angular project to $PROJECT_NAME"
          git push origin main

      - name: Comentar na issue
        run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "✅ O repositório **$PROJECT_NAME** foi criado com sucesso: https://github.com/vyracare/$PROJECT_NAME"
